sudo: true
dist: trusty

language: c

addons:
  apt:
    packages:
      - libconfig-dev
      - libprocps3-dev

before_script:
  - autoreconf --install && mkdir build && cd build

script:
  - ../configure && make && make check
  - cat test/test-suite.log
  - ../configure --enable-libconfig --enable-server && make && make check
  - cat test/test-suite.log
