sudo: false

language: c

addons:
  apt:
    packages:
      - libconfig-dev
      - libprocps3-dev

before_script:
  - autoreconf --install && mkdir build && cd build

script:
  - ../configure && make && make check
  - ../configure --enable-libconfig --enable-server && make && make check
