sudo: required
dist: trusty

language: c

install:
  - sudo apt-get update
  - sudo apt-get -y install libconfig-dev libprocps3-dev

before_script:
  - autoreconf --install && mkdir build && cd build

script:
  - ../configure && make && make check
  - ../configure --enable-libconfig --enable-server && make && make check
